import os

# Get project root directory (parent of backend/)
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# --- Milvus settings ---
MILVUS_HOST = "localhost"
MILVUS_PORT = "19530"
KEYFRAME_COLLECTION_NAME = "video_keyframes"
# CLIP ViT-B-32 produces 512-dimensional embeddings; keep this in sync with model choice
VECTOR_DIMENSION = 512

# Compatibility aliases / service URLs (used by scripts expecting these names)
# Elasticsearch
ELASTICSEARCH_URL = "http://localhost:9200"

# MinIO (object storage)
MINIO_ENDPOINT = "http://localhost:9000"
MINIO_ACCESS_KEY = "minioadmin"
MINIO_SECRET_KEY = "minioadmin"
MINIO_BUCKET = "milvus"

# --- Data paths (absolute from project root) ---
CLIP_FEATURES_DIR = os.path.join(ROOT_DIR, "data", "embeddings")
# Backwards compatibility alias
EMBEDDINGS_DIR = CLIP_FEATURES_DIR
KEYFRAMES_DIR = os.path.join(ROOT_DIR, "data", "keyframes")
TRANSCRIPTS_DIR = os.path.join(ROOT_DIR, "data", "transcripts")
VIDEOS_DIR = os.path.join(ROOT_DIR, "data", "videos")

# --- Model ---
# Use a smaller CLIP backbone by default to speed up embedding computation.
# Change to a lighter model (ViT-B) to trade a small amount of accuracy for much faster runtime.
CLIP_MODEL_NAME = "ViT-B-32"
# Recommended pretrained source for ViT-B; open_clip will attempt to load the pretrained weights.
CLIP_PRETRAINED = "openai"

OBJECT_LABELS = [
    "Tortoise",
    "Container",
    "Magpie",
    "Sea turtle",
    "Football",
    "Ambulance",
    "Ladder",
    "Toothbrush",
    "Syringe",
    "Sink",
    "Toy",
    "Organ",
    "Cassette deck",
    "Apple",
    "Human eye",
    "Cosmetics",
    "Paddle",
    "Snowman",
    "Beer",
    "Chopsticks",
    "Human beard",
    "Bird",
    "Parking meter",
    "Traffic light",
    "Croissant",
    "Cucumber",
    "Radish",
    "Towel",
    "Doll",
    "Skull",
    "Washing machine",
    "Glove",
    "Tick",
    "Belt",
    "Sunglasses",
    "Banjo",
    "Cart",
    "Ball",
    "Backpack",
    "Bicycle",
    "Home appliance",
    "Centipede",
    "Boat",
    "Surfboard",
    "Boot",
    "Headphones",
    "Hot dog",
    "Shorts",
    "Fast food",
    "Bus",
    "Boy",
    "Screwdriver",
    "Bicycle wheel",
    "Barge",
    "Laptop",
    "Miniskirt",
    "Drill",
    "Dress",
    "Bear",
    "Waffle",
    "Pancake",
    "Brown bear",
    "Woodpecker",
    "Blue jay",
    "Pretzel",
    "Bagel",
    "Tower",
    "Teapot",
    "Person",
    "Bow and arrow",
    "Swimwear",
    "Beehive",
    "Brassiere",
    "Bee",
    "Bat",
    "Starfish",
    "Popcorn",
    "Burrito",
    "Chainsaw",
    "Balloon",
    "Wrench",
    "Tent",
    "Vehicle registration plate",
    "Lantern",
    "Toaster",
    "Flashlight",
    "Billboard",
    "Tiara",
    "Limousine",
    "Necklace",
    "Carnivore",
    "Scissors",
    "Stairs",
    "Computer keyboard",
    "Printer",
    "Traffic sign",
    "Chair",
    "Shirt",
    "Poster",
    "Cheese",
    "Sock",
    "Fire hydrant",
    "Land vehicle",
    "Earrings",
    "Tie",
    "Watercraft",
    "Cabinetry",
    "Suitcase",
    "Muffin",
    "Bidet",
    "Snack",
    "Snowmobile",
    "Clock",
    "Medical equipment",
    "Cattle",
    "Cello",
    "Jet ski",
    "Camel",
    "Coat",
    "Suit",
    "Desk",
    "Cat",
    "Bronze sculpture",
    "Juice",
    "Gondola",
    "Beetle",
    "Cannon",
    "Computer mouse",
    "Cookie",
    "Office building",
    "Fountain",
    "Coin",
    "Calculator",
    "Cocktail",
    "Computer monitor",
    "Box",
    "Stapler",
    "Christmas tree",
    "Cowboy hat",
    "Hiking equipment",
    "Studio couch",
    "Drum",
    "Dessert",
    "Wine rack",
    "Drink",
    "Zucchini",
    "Ladle",
    "Human mouth",
    "Dairy",
    "Dice",
    "Oven",
    "Dinosaur",
    "Ratchet",
    "Couch",
    "Cricket ball",
    "Winter melon",
    "Spatula",
    "Whiteboard",
    "Pencil sharpener",
    "Door",
    "Hat",
    "Shower",
    "Eraser",
    "Fedora",
    "Guacamole",
    "Dagger",
    "Scarf",
    "Dolphin",
    "Sombrero",
    "Tin can",
    "Mug",
    "Tap",
    "Harbor seal",
    "Stretcher",
    "Can opener",
    "Goggles",
    "Human body",
    "Roller skates",
    "Coffee cup",
    "Cutting board",
    "Blender",
    "Plumbing fixture",
    "Stop sign",
    "Office supplies",
    "Volleyball",
    "Vase",
    "Slow cooker",
    "Wardrobe",
    "Coffee",
    "Whisk",
    "Paper towel",
    "Personal care",
    "Food",
    "Sun hat",
    "Tree house",
    "Flying disc",
    "Skirt",
    "Gas stove",
    "Salt and pepper shakers",
    "Mechanical fan",
    "Face powder",
    "Fax",
    "Fruit",
    "French fries",
    "Nightstand",
    "Barrel",
    "Kite",
    "Tart",
    "Treadmill",
    "Fox",
    "Flag",
    "Horn",
    "Window blind",
    "Human foot",
    "Golf cart",
    "Jacket",
    "Egg",
    "Street light",
    "Guitar",
    "Pillow",
    "Human leg",
    "Isopod",
    "Grape",
    "Human ear",
    "Power plugs and sockets",
    "Panda",
    "Giraffe",
    "Woman",
    "Door handle",
    "Rhinoceros",
    "Bathtub",
    "Goldfish",
    "Houseplant",
    "Goat",
    "Baseball bat",
    "Baseball glove",
    "Mixing bowl",
    "Marine invertebrates",
    "Kitchen utensil",
    "Light switch",
    "House",
    "Horse",
    "Stationary bicycle",
    "Hammer",
    "Ceiling fan",
    "Sofa bed",
    "Adhesive tape",
    "Harp",
    "Sandal",
    "Bicycle helmet",
    "Saucer",
    "Harpsichord",
    "Human hair",
    "Heater",
    "Harmonica",
    "Hamster",
    "Curtain",
    "Bed",
    "Kettle",
    "Fireplace",
    "Scale",
    "Drinking straw",
    "Insect",
    "Hair dryer",
    "Kitchenware",
    "Indoor rower",
    "Invertebrate",
    "Food processor",
    "Bookcase",
    "Refrigerator",
    "Wood-burning stove",
    "Punching bag",
    "Common fig",
    "Cocktail shaker",
    "Jaguar",
    "Golf ball",
    "Fashion accessory",
    "Alarm clock",
    "Filing cabinet",
    "Artichoke",
    "Table",
    "Tableware",
    "Kangaroo",
    "Koala",
    "Knife",
    "Bottle",
    "Bottle opener",
    "Lynx",
    "Lavender",
    "Lighthouse",
    "Dumbbell",
    "Human head",
    "Bowl",
    "Humidifier",
    "Porch",
    "Lizard",
    "Billiard table",
    "Mammal",
    "Mouse",
    "Motorcycle",
    "Musical instrument",
    "Swim cap",
    "Frying pan",
    "Snowplow",
    "Bathroom cabinet",
    "Missile",
    "Bust",
    "Man",
    "Waffle iron",
    "Milk",
    "Ring binder",
    "Plate",
    "Mobile phone",
    "Baked goods",
    "Mushroom",
    "Crutch",
    "Pitcher",
    "Mirror",
    "Lifejacket",
    "Table tennis racket",
    "Pencil case",
    "Musical keyboard",
    "Scoreboard",
    "Briefcase",
    "Kitchen knife",
    "Nail",
    "Tennis ball",
    "Plastic bag",
    "Oboe",
    "Chest of drawers",
    "Ostrich",
    "Piano",
    "Girl",
    "Plant",
    "Potato",
    "Hair spray",
    "Sports equipment",
    "Pasta",
    "Penguin",
    "Pumpkin",
    "Pear",
    "Infant bed",
    "Polar bear",
    "Mixer",
    "Cupboard",
    "Jacuzzi",
    "Pizza",
    "Digital clock",
    "Pig",
    "Reptile",
    "Rifle",
    "Lipstick",
    "Skateboard",
    "Raven",
    "High heels",
    "Red panda",
    "Rose",
    "Rabbit",
    "Sculpture",
    "Saxophone",
    "Shotgun",
    "Seafood",
    "Submarine sandwich",
    "Snowboard",
    "Sword",
    "Picture frame",
    "Sushi",
    "Loveseat",
    "Ski",
    "Squirrel",
    "Tripod",
    "Stethoscope",
    "Submarine",
    "Scorpion",
    "Segway",
    "Training bench",
    "Snake",
    "Coffee table",
    "Skyscraper",
    "Sheep",
    "Television",
    "Trombone",
    "Tea",
    "Tank",
    "Taco",
    "Telephone",
    "Torch",
    "Tiger",
    "Strawberry",
    "Trumpet",
    "Tree",
    "Tomato",
    "Train",
    "Tool",
    "Picnic basket",
    "Cooking spray",
    "Trousers",
    "Bowling equipment",
    "Football helmet",
    "Truck",
    "Measuring cup",
    "Coffeemaker",
    "Violin",
    "Vehicle",
    "Handbag",
    "Paper cutter",
    "Wine",
    "Weapon",
    "Wheel",
    "Worm",
    "Wok",
    "Whale",
    "Zebra",
    "Auto part",
    "Jug",
    "Pizza cutter",
    "Cream",
    "Monkey",
    "Lion",
    "Bread",
    "Platter",
    "Chicken",
    "Eagle",
    "Helicopter",
    "Owl",
    "Duck",
    "Turtle",
    "Hippopotamus",
    "Crocodile",
    "Toilet",
    "Toilet paper",
    "Squid",
    "Clothing",
    "Footwear",
    "Lemon",
    "Spider",
    "Deer",
    "Frog",
    "Banana",
    "Rocket",
    "Wine glass",
    "Countertop",
    "Tablet computer",
    "Waste container",
    "Swimming pool",
    "Dog",
    "Book",
    "Elephant",
    "Shark",
    "Candle",
    "Leopard",
    "Axe",
    "Hand dryer",
    "Soap dispenser",
    "Porcupine",
    "Flower",
    "Canary",
    "Cheetah",
    "Palm tree",
    "Hamburger",
    "Maple",
    "Building",
    "Fish",
    "Lobster",
    "Asparagus",
    "Furniture",
    "Hedgehog",
    "Airplane",
    "Spoon",
    "Otter",
    "Bull",
    "Oyster",
    "Horizontal bar",
    "Convenience store",
    "Bomb",
    "Bench",
    "Ice cream",
    "Caterpillar",
    "Butterfly",
    "Parachute",
    "Orange",
    "Antelope",
    "Beaker",
    "Moths and butterflies",
    "Window",
    "Closet",
    "Castle",
    "Jellyfish",
    "Goose",
    "Mule",
    "Swan",
    "Peach",
    "Coconut",
    "Seat belt",
    "Raccoon",
    "Chisel",
    "Fork",
    "Lamp",
    "Camera",
    "Squash",
    "Racket",
    "Human face",
    "Human arm",
    "Vegetable",
    "Diaper",
    "Unicycle",
    "Falcon",
    "Chime",
    "Snail",
    "Shellfish",
    "Cabbage",
    "Carrot",
    "Mango",
    "Jeans",
    "Flowerpot",
    "Pineapple",
    "Drawer",
    "Stool",
    "Envelope",
    "Cake",
    "Dragonfly",
    "Sunflower",
    "Microwave oven",
    "Honeycomb",
    "Marine mammal",
    "Sea lion",
    "Ladybug",
    "Shelf",
    "Watch",
    "Candy",
    "Salad",
    "Parrot",
    "Handgun",
    "Sparrow",
    "Van",
    "Grinder",
    "Spice rack",
    "Light bulb",
    "Corded phone",
    "Sports uniform",
    "Tennis racket",
    "Wall clock",
    "Serving tray",
    "Kitchen & dining room table",
    "Dog bed",
    "Cake stand",
    "Cat furniture",
    "Bathroom accessory",
    "Facial tissue holder",
    "Pressure cooker",
    "Kitchen appliance",
    "Tire",
    "Ruler",
    "Luggage and bags",
    "Microphone",
    "Broccoli",
    "Umbrella",
    "Pastry",
    "Grapefruit",
    "Band-aid",
    "Animal",
    "Bell pepper",
    "Turkey",
    "Lily",
    "Pomegranate",
    "Doughnut",
    "Glasses",
    "Human nose",
    "Pen",
    "Ant",
    "Car",
    "Aircraft",
    "Human hand",
    "Skunk",
    "Teddy bear",
    "Watermelon",
    "Cantaloupe",
    "Dishwasher",
    "Flute",
    "Balance beam",
    "Sandwich",
    "Shrimp",
    "Sewing machine",
    "Binoculars",
    "Rays and skates",
    "Ipod",
    "Accordion",
    "Willow",
    "Crab",
    "Crown",
    "Seahorse",
    "Perfume",
    "Alpaca",
    "Taxi",
    "Canoe",
    "Remote control",
    "Wheelchair",
    "Rugby ball",
    "Armadillo",
    "Maracas",
    "Helmet",
]

# --- Elasticsearch settings ---
ELASTIC_HOST = "localhost"
ELASTIC_PORT = "9200"
ELASTIC_SCHEME = "http"
TRANSCRIPT_INDEX = "video_transcripts"
DEFAULT_FALLBACK_FPS = 25

# --- Evaluation Server Settings ---
# ⚠️ KHI SERVER THAY ĐỔI → CHỈ SỬA 3 DÒNG DƯỚI ĐÂY
EVAL_SERVER_URL = "http://192.168.20.156:5601"  # ← Đổi IP/domain server mới
SESSION_ID = "LIj1h0LIHorVZYS7hXUe9bMbDxGJBmg-"  # ← Đổi session ID mới
EVALUATION_ID = "44457530-7aaa-4186-a4df-bcbaf9908d33"  # ← Đổi evaluation ID mới

# Credentials (không dùng nếu có SESSION_ID sẵn)
EVAL_USERNAME = "team006"
EVAL_PASSWORD = "123456"
